
---
title: "Water Resources Metrics"
author: Umit Taner
date: February, 2020
output: revealjs::revealjs_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r data}

library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)

source("mReliability.R")
source("mVulnerability.R")
source("mResilience.R")

# Data
dem <- c(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)
sup <- c(100, 100, 80, 70, 50, 90, 100, 100, 60, 90, 100, 50, 100, 100, 100)

df <- tibble(Demand = dem, Delivery = sup) %>% mutate(mon = 1:n()) %>%
  gather(variable, value, -mon)

```

## Sample Data

<table><tr><td>
```{r table}
p <- ggplot(df, aes(x = mon, y = value, color = variable)) + 
  geom_line(size = 1) +
  theme_light() +
  labs(x = "Months", y = "Million m3") +
  scale_x_continuous(breaks = seq(1,15,1)); p
```

</td><td>


```{r table2}

df_display <- df %>% spread(variable, value)

df_display %>% kable() %>% kable_styling()

#grid::grid.newpage()
#gridExtra::grid.table(df_display, theme = ttheme_minimal())

```
</td></tr></table>



```{r cars}

#mReliability(dem, sup, type = "time-based")
#mReliability(dem, sup, type = "volumetric")
#mVulnerability(dem, sup)
 

```
